# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\teste_login.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(649, 620)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblUsuario = QtWidgets.QLabel(self.centralwidget)
        self.lblUsuario.setGeometry(QtCore.QRect(310, 185, 71, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblUsuario.setFont(font)
        self.lblUsuario.setToolTip("")
        self.lblUsuario.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblUsuario.setObjectName("lblUsuario")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 209, 291, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lblSenha = QtWidgets.QLabel(self.centralwidget)
        self.lblSenha.setGeometry(QtCore.QRect(310, 266, 51, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lblSenha.setFont(font)
        self.lblSenha.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblSenha.setObjectName("lblSenha")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 290, 291, 21))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 340, 291, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(310, 410, 291, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lblCadastrar = QtWidgets.QLabel(self.centralwidget)
        self.lblCadastrar.setGeometry(QtCore.QRect(310, 390, 191, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblCadastrar.setFont(font)
        self.lblCadastrar.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblCadastrar.setObjectName("lblCadastrar")
        self.lblTituloLogin = QtWidgets.QLabel(self.centralwidget)
        self.lblTituloLogin.setGeometry(QtCore.QRect(310, 130, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.lblTituloLogin.setFont(font)
        self.lblTituloLogin.setStyleSheet("color: rgb(255, 255, 255);")
        self.lblTituloLogin.setScaledContents(True)
        self.lblTituloLogin.setObjectName("lblTituloLogin")
        self.lblImagemDeFundo = QtWidgets.QLabel(self.centralwidget)
        self.lblImagemDeFundo.setGeometry(QtCore.QRect(0, 0, 651, 601))
        self.lblImagemDeFundo.setStyleSheet("background-image: url(:/Login/Login_imagem.png);")
        self.lblImagemDeFundo.setText("")
        self.lblImagemDeFundo.setPixmap(QtGui.QPixmap("Login_imagem.png"))
        self.lblImagemDeFundo.setScaledContents(True)
        self.lblImagemDeFundo.setObjectName("lblImagemDeFundo")
        self.lblImagemDeFundo.raise_()
        self.lineEdit.raise_()
        self.lblUsuario.raise_()
        self.lineEdit_2.raise_()
        self.lblSenha.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.lblCadastrar.raise_()
        self.lblTituloLogin.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit, self.lineEdit_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblUsuario.setText(_translate("MainWindow", "Usuario"))
        self.lblSenha.setText(_translate("MainWindow", "Senha"))
        self.pushButton.setText(_translate("MainWindow", "Entrar"))
        self.pushButton_2.setText(_translate("MainWindow", "Cadastrar"))
        self.lblCadastrar.setText(_translate("MainWindow", "Não tem cadastro? Cadastre-se"))
        self.lblTituloLogin.setText(_translate("MainWindow", "Login"))

#import Login_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

